# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osm_speed_data.proto
"""Generated protocol buffer code."""
from ctypes.wintypes import POINT
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14osm_speed_data.proto\x12\x0eopenpilot.maps\",\n\x05Point\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"}\n\x11SpeedLimitSegment\x12\x12\n\nosm_way_id\x18\x01 \x01(\x03\x12\'\n\x08geometry\x18\x02 \x03(\x0b\x32\x15.openpilot.maps.Point\x12\x12\n\ncurvatures\x18\x03 \x03(\x02\x12\x17\n\x0fspeed_limit_mps\x18\x04 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osm_speed_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  POINT._serialized_start=40
  _POINT._serialized_end=84
  _SPEEDLIMITSEGMENT._serialized_start=86
  _SPEEDLIMITSEGMENT._serialized_end=211
# @@protoc_insertion_point(module_scope)
