# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tools/map_processing/osm_speed_data.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'tools/map_processing/osm_speed_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)tools/map_processing/osm_speed_data.proto\x12\x0eopenpilot.maps\",\n\x05Point\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"\xa3\x01\n\x11SpeedLimitSegment\x12\x12\n\nosm_way_id\x18\x01 \x01(\x03\x12\'\n\x08geometry\x18\x02 \x03(\x0b\x32\x15.openpilot.maps.Point\x12\x12\n\ncurvatures\x18\x03 \x03(\x02\x12\x17\n\x0fspeed_limit_mps\x18\x04 \x01(\x02\x12$\n\x1c\x63urvature_derived_speeds_mps\x18\x05 \x03(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tools.map_processing.osm_speed_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT']._serialized_start=61
  _globals['_POINT']._serialized_end=105
  _globals['_SPEEDLIMITSEGMENT']._serialized_start=108
  _globals['_SPEEDLIMITSEGMENT']._serialized_end=271
# @@protoc_insertion_point(module_scope)
